"""视频下载：基于 yt-dlp。支持 YouTube / TikTok 等站点。

cookie 来源（按优先级）：
- YouTube: config.yaml `download.cookies.youtube` → 环境变量 `YOUTUBE_COOKIES_FILE`
- TikTok:  config.yaml `download.cookies.tiktok` → 环境变量 `TIKTOK_COOKIES_BROWSER`（浏览器名，如 edge）
"""
import os
from pathlib import Path
from urllib.parse import urlparse

from ..utils.logging import get_logger

log = get_logger(__name__)


def is_url(text) -> bool:
    return str(text).startswith(("http://", "https://"))


def _build_cookie_opts(url, cookies_config):
    """根据 URL 域名构造 yt-dlp 的 cookie 相关 opts。

    cookie 来源优先级：
    - config.yaml `download.cookies.<platform>`（高级）
    - 环境变量 `YOUTUBE_COOKIES_FILE` / `TIKTOK_COOKIES_FILE`（设置页粘贴 JSON 后自动写入的路径）
    - TikTok 备选：`TIKTOK_COOKIES_BROWSER`（从浏览器读取登录 cookie）
    """
    cookies_config = cookies_config or {}
    domain = (urlparse(str(url)).netloc or "").lower()
    opts = {}
    if "youtube.com" in domain or "youtu.be" in domain:
        cf = (cookies_config.get("youtube") or None) or os.environ.get("YOUTUBE_COOKIES_FILE") or None
        if cf:
            opts["cookiefile"] = str(cf)
    elif "tiktok.com" in domain:
        cf = (cookies_config.get("tiktok") or None) or os.environ.get("TIKTOK_COOKIES_FILE") or None
        if cf:
            opts["cookiefile"] = str(cf)
        else:
            browser = os.environ.get("TIKTOK_COOKIES_BROWSER") or None
            if browser:
                opts["cookiesfrombrowser"] = (browser.strip(),)
    return opts


# yt-dlp 报错中与「需要登录/被风控」相关的关键词
_COOKIE_ERROR_HINTS = (
    "sign in to confirm", "you're not a bot", "not a bot",
    "login required", "log in", "only available to members",
    "confirm your age", "verify you are human", "bot check",
    "http error 403",
)


def _is_cookie_error(err_text: str) -> bool:
    t = (err_text or "").lower()
    return any(h in t for h in _COOKIE_ERROR_HINTS)


def _is_page_reload_error(err_text: str) -> bool:
    """YouTube 反爬：'The page needs to be reloaded'。"""
    t = (err_text or "").lower()
    return "page needs to be reloaded" in t


def _normalize_cookies_file(path):
    """把 cookie 文件统一为 yt-dlp 可用的格式。

    返回 (cookiefile, http_headers)：
    - JSON（Cookie-Editor 插件导出）→ 自动转换成 Netscape 格式文件
    - Netscape 格式（# Netscape 头 / 制表符分隔）→ 原样使用
    - Cookie header 字符串（"name=value; name2=value2"）→ 通过 http_headers 传递
    """
    import json as _json

    p = Path(path)
    if not p.exists():
        return None, None
    raw = p.read_text(encoding="utf-8", errors="replace").strip()
    stripped = raw.lstrip("\ufeff")
    if not stripped:
        return None, None

    # 1) JSON 数组（Cookie-Editor 等扩展导出）
    if stripped.startswith("[") or stripped.startswith("{"):
        try:
            data = _json.loads(stripped)
        except Exception:
            raise RuntimeError("[Download] Cookie JSON 解析失败，请用 Cookie-Editor 重新导出后粘贴")
        if isinstance(data, dict):
            for k in ("cookies", "items", "cookie"):
                if isinstance(data.get(k), list):
                    data = data[k]
                    break
        lines = ["# Netscape HTTP Cookie File", "# Generated by PolyDub from JSON export", ""]
        for c in data if isinstance(data, list) else []:
            if not isinstance(c, dict):
                continue
            domain = str(c.get("domain") or "").lstrip(".")
            name = c.get("name")
            if not domain or not name:
                continue
            domain = "." + domain if "." in domain else domain
            path_s = c.get("path") or "/"
            secure = "TRUE" if c.get("secure") else "FALSE"
            try:
                exp = int(float(c.get("expirationDate") or c.get("expires") or 0))
            except Exception:
                exp = 0
            lines.append(f"{domain}\tTRUE\t{path_s}\t{secure}\t{exp}\t{name}\t{c.get('value', '')}")
        out = p.with_suffix(".netscape.txt")
        out.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return str(out), None

    # 2) 已是 Netscape 格式
    if stripped.startswith("# Netscape") or stripped.startswith("#HttpOnly") or "\t" in stripped:
        return str(p), None

    # 3) 其它一律视为 Cookie header 字符串："name=value; name2=value2"（或 "Cookie: ..."）
    hdr = stripped
    if hdr.lower().startswith("cookie:"):
        hdr = hdr[len("cookie:"):].strip()
    return None, {"Cookie": hdr}


def _progress(d):
    """yt-dlp 进度回调（记录到日志）。"""
    status = d.get("status")
    if status == "downloading":
        pct = (d.get("_percent_str") or "").strip()
        speed = (d.get("_speed_str") or "").strip()
        eta = (d.get("_eta_str") or "").strip()
        log.info("[Download] %s %s ETA %s", pct, speed, eta)
    elif status == "finished":
        log.info("[Download] 下载完成，正在合并封装 ...")


def download(url, out_dir, cookies_config=None, format_spec="bestvideo+bestaudio/best",
             show_progress=False):
    """下载视频到 out_dir，返回 (文件路径, info)。失败抛异常。"""
    try:
        from yt_dlp import YoutubeDL
    except ImportError:
        raise RuntimeError("[Download] 未安装 yt-dlp，请先 `pip install yt-dlp`")

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    cookie_opts = _build_cookie_opts(url, cookies_config)
    if cookie_opts.get("cookiefile") and not Path(cookie_opts["cookiefile"]).exists():
        log.warning("[Download] cookie 文件不存在，已忽略：%s", cookie_opts["cookiefile"])
        cookie_opts.pop("cookiefile")
    # 自动适配 cookie 格式：JSON（Cookie-Editor）→ Netscape；header 字符串 → http_headers
    if cookie_opts.get("cookiefile"):
        cf, hdrs = _normalize_cookies_file(cookie_opts["cookiefile"])
        if cf:
            cookie_opts["cookiefile"] = cf
        else:
            cookie_opts.pop("cookiefile", None)
        if hdrs:
            cookie_opts.setdefault("http_headers", {}).update(hdrs)
            log.info("[Download] 使用 Cookie header 字符串")

    opts = {
        "outtmpl": str(out_dir / "%(title)s [%(id)s].%(ext)s"),
        "format": format_spec,
        "noplaylist": True,
        "merge_output_format": "mp4",
        "quiet": True,
        "no_warnings": True,
    }
    opts.update(cookie_opts)
    if show_progress:
        opts["progress_hooks"] = [_progress]

    log.info("[Download] 开始下载 %s", url)
    if cookie_opts.get("cookiefile"):
        log.info("[Download] 使用 cookie：%s", cookie_opts["cookiefile"])
    if cookie_opts.get("cookiesfrombrowser"):
        log.info("[Download] 使用浏览器 cookie：%s", cookie_opts["cookiesfrombrowser"][0])

    # YouTube：依次尝试多个 player client，绕开“页面需要重载”等反爬拦截
    _YT_CLIENTS = ["default", "android", "web_embedded", "tv", "mweb"]
    _is_yt = "youtube.com" in str(url) or "youtu.be" in str(url)
    last_err = None
    saw_reload = False
    for _client in _YT_CLIENTS if _is_yt else ["default"]:
        o = dict(opts)
        ea = {"youtube": {"challenge_solver": "default"}}  # 有 node/deno 时解 n 挑战，恢复隐藏格式
        if _client != "default":
            ea["youtube"]["player_client"] = [_client]
        o["extractor_args"] = ea
        try:
            with YoutubeDL(o) as ydl:
                info = ydl.extract_info(url, download=True)
            break  # 成功
        except Exception as e:
            last_err = e
            if _is_page_reload_error(str(e)):
                saw_reload = True
            if not _is_yt:
                raise
            log.warning("[Download] player_client=%s 失败，尝试下一个：%s", _client, str(e)[:120])
    else:
        if saw_reload:
            raise RuntimeError(
                "[Download] YouTube 反爬拦截（页面需要重载）。\n"
                "请依次尝试：① 更换代理节点/线路（当前出口 IP 可能被 YouTube 标记）；"
                "② 重新登录 YouTube 后重新导出最新 cookie 并粘贴保存；"
                "③ 稍等几分钟再试（频繁请求会触发风控）。"
            ) from last_err
        if _is_cookie_error(str(last_err)):
            raise RuntimeError(
                "[Download] 下载失败：可能需要登录 Cookie（被风控/需登录/会员/年龄限制）。\n"
                "解决办法：在 Web UI「设置」页 →『下载 Cookie（YouTube / TikTok）』中，"
                "用浏览器插件 Cookie-Editor 导出对应网站的 cookie（JSON）整段粘贴保存后重试。"
            ) from last_err
        raise last_err

    filepath = None
    if info:
        rd = info.get("requested_downloads") or []
        if rd:
            filepath = rd[-1].get("filepath")
        if not filepath:
            filepath = ydl.prepare_filename(info)

    if not filepath or not Path(filepath).exists():
        raise RuntimeError(f"[Download] 下载失败：未找到输出文件（url={url}）")

    log.info("[Download] 完成 -> %s", filepath)
    return str(filepath), info
