SPEAKER_00:
  role: SPEAKER_00
  voice: null
SPEAKER_01:
  role: SPEAKER_01
  voice: null
SPEAKER_02:
  role: SPEAKER_02
  voice: null
SPEAKER_03:
  role: SPEAKER_03
  voice: null
SPEAKER_04:
  role: SPEAKER_04
  voice: null
SPEAKER_05:
  role: SPEAKER_05
  voice: null
SPEAKER_06:
  role: SPEAKER_06
  voice: null
